analytics: {}
color:
  brandColors:
    - '#10102D'
    - '#47474F'
    - '#C1C4A5'
    - '#848D7B'
    - '#F4F4FC'
  brandStrength: 1
  lightness: 0.5
  rhythmicContrast: 0.802927
  saturation: 0.671171
cta: {}
layout_spectrum: 0.41554
name: Iced Liberty
opengraph: {}
purpose:
  - name: engagement
typography_spectrum: 0.394144
